#!/bin/bash
# onboarding-ledger-write-gate.sh — schema + state-machine integrity gate
#                                   for writes to the onboarding status
#                                   ledger.
#
# Hook    : PreToolUse:Write|Edit
# Mode    : DENY (blocks the write before it lands on disk)
# State   : validates shape via hooks/lib/validator.bundle.mjs (the
#           onboarding-status schema is inlined in the bundle at build
#           time; source schemas/onboarding-status.schema.json), plus the
#           pre-existing tests/e2e/docs/onboarding-status.json
#           (when present) to validate the state-machine transition.
# Env     : none
#
# Why
# ---
# The ledger is the single source of truth for the pipeline state. A
# corrupted ledger silently degrades every downstream gate
# (onboarding-ledger-gate, workflow-reviewer briefings). This hook is the
# guard at the only mutation point.
#
# What it gates
# -------------
# 1. **Shape validation.** The proposed contents must validate against
#    the onboarding-status schema inlined in hooks/lib/validator.bundle.mjs
#    (source: schemas/onboarding-status.schema.json). When node or the
#    bundle is unavailable, the schema portion is skipped but the
#    non-node checks (state-machine, actor-identity, mode-auth, per-phase
#    deliverables) still fire and jq parseability is enforced.
# 2. **No phase-skip transitions.** A write that bumps `currentPhase` from
#    N to N+2 with N+1 still `pending` is denied — every phase must
#    progress through `pending → in-progress → completed` in order
#    (skip-deviations are recorded by setting status: skipped + populating
#    `approvedDeviations[]`).
# 3. **No reviewerVerdict: approved without a handoverEnvelope.** A phase
#    cannot be approved unless the closing subagent's handover envelope
#    is captured in the same record.
# 4. **Actor-identity on approval transitions.** Any write that
#    transitions a phase's `reviewerVerdict` from non-approved to
#    `approved` MUST come from a registered approver subagent context.
#    Orchestrator-direct writes that approve a phase are denied — only
#    `workflow-reviewer-*` / `phase-validator-*` dispatches (tracked by
#    workflow-approver-registry.sh) can record approvals. This is the
#    separation-of-duties gate: the orchestrator does the work, an
#    approver subagent records the verdict. The same identity is required
#    for a top-level `.status` → `complete` | `aborted` transition: that
#    write retires the session's activation marker (and with it every
#    achilles gate and the kernel-mandate role binding), so the
#    orchestrator may not land its own off-switch.
# 5. **Mode authorisation.** Any write that sets or changes `runMode`
#    (the coverage-expansion mode — `standard` vs `depth`) MUST also
#    include a non-empty `modeAuthorizer` field capturing the user's
#    explicit choice (verbatim quote). The schema permits `runMode` to
#    be persisted; this gate forces it to be persisted with an audit
#    trail of who chose it. Prevents the orchestrator from silently
#    defaulting to a mode without asking.
# 6. **Silent-allow for non-ledger writes.** Only files whose path ends
#    with `tests/e2e/docs/onboarding-status.json` are gated.
# 7. **Silent-allow when the file is missing AND the write has no
#    approvals.** A fresh-run ledger init with all phases pending has
#    no actor-identity check (nothing is being approved).
#
# Canonical reference
# -------------------
# schemas/onboarding-status.schema.json
# skills/onboarding/SKILL.md §"Status ledger + workflow reviewer"
# hooks/lib/validator.bundle.mjs (generated by `npm run build:validator`)
#
# Failure → action
# ----------------
# Shape invalid                    → DENY with schema-path + bad field
# Phase-skip without approval      → DENY naming the missing in-between phase
# reviewerVerdict approved w/o handover → DENY naming the empty field

set -uo pipefail

# shellcheck disable=SC1091
. "$(dirname "${BASH_SOURCE[0]}")/lib/pipeline-ledger-write.sh"
hook_jq_init fatal

pipeline_config onboarding
PIPELINE_SCHEMA_NAME="onboarding-status"
PIPELINE_APPROVER_TYPES="workflow-reviewer phase-validator process-validator"
PIPELINE_PHASE_COUNT=8
PIPELINE_MSG_PHASE_LABEL='Phase'
PIPELINE_MSG_DELIVERABLE_LEDGER='ledger'
PIPELINE_MSG_DELIVERABLE_WHY=' The deliverables are unforgeable signatures of the correct
skill having been invoked — without them, the phase was either skipped
or shortcut.'

# ---------------------------------------------------------------------------
# Per-phase positive-deliverable checks (Phase-N → completed transitions).
# When a phase's status flips from non-completed to "completed" in the
# proposed write, the canonical deliverables for that phase must already
# exist on disk. This catches "orchestrator marked the phase done without
# actually producing the deliverables" — the failure mode that
# markdown-text contract enforcement alone could not stop.
#
# Per-phase manifests (minimum required files / sentinel checks):
#
#   Phase 4 (Journey-mapping):
#     - tests/e2e/docs/journey-map.md exists AND line 1 == the sentinel
#       `<!-- journey-mapping:generated -->`.
#     - tests/e2e/docs/.phase4-cycle-state.json exists AND contains at
#       minimum cycles."1" + cycles."2" entries (cycle 1 discovery +
#       cycle 2 edge-probe — non-negotiable per journey-mapping/SKILL.md
#       §"Iterative discovery cycles").
#
#   Phase 5 (Coverage-expansion):
#     - tests/e2e/docs/coverage-expansion-state.json exists AND contains
#       at minimum passes."1" (the strict-per-journey first pass).
#
#   Phase 6 (Bug-discovery):
#     - tests/e2e/docs/adversarial-findings.md exists.
#
#   Phase 7 (Secrets-sweep):
#     - .env.example exists at the project root.
#
#   Phase 8 (Report):
#     - qa-summary-deck.html AND qa-summary-deck.pdf exist at the
#       project root.
#
# Phases 1-3 are not enforced here — their deliverables (config files,
# fixtures, happy-path specs) don't have unforgeable signatures the
# harness can verify cheaply. The ledger's `phases[N].deliverables[]`
# array is the audit trail for those phases; the orchestrator-to-
# reviewer brief gate ensures the reviewer reads them.
# ---------------------------------------------------------------------------
onboarding_check_deliverables() {
  case "$1" in
    4)
      # Phase 4 — journey-map.md + sentinel + cycle-state with cycles 1 & 2.
      MAP_PATH="$PROJECT_ROOT/tests/e2e/docs/journey-map.md"
      CYCLE_STATE_PATH="$PROJECT_ROOT/tests/e2e/docs/.phase4-cycle-state.json"

      if [ ! -f "$MAP_PATH" ]; then
        pipeline_emit_phase_deny "4" \
          "tests/e2e/docs/journey-map.md does not exist." \
          "invoke the \`journey-mapping\` skill via the Skill tool. It runs the iterative discovery cycle protocol and writes the map with the line-1 sentinel." \
          "skills/onboarding/SKILL.md §\"Phase 4 — Journey mapping\" + skills/journey-mapping/SKILL.md"
      fi

      FIRST_LINE=$(head -n 1 "$MAP_PATH" 2>/dev/null || echo "")
      if [ "$FIRST_LINE" != "<!-- journey-mapping:generated -->" ]; then
        pipeline_emit_phase_deny "4" \
          "tests/e2e/docs/journey-map.md is missing the line-1 sentinel \`<!-- journey-mapping:generated -->\`. Got: \"${FIRST_LINE:0:80}\"" \
          "regenerate the map via the journey-mapping skill. The sentinel is its authorship marker — without it the map is forged." \
          "skills/journey-mapping/SKILL.md §\"Recognizing a previously-generated journey map\""
      fi

      if [ ! -f "$CYCLE_STATE_PATH" ]; then
        pipeline_emit_phase_deny "4" \
          "tests/e2e/docs/.phase4-cycle-state.json does not exist." \
          "the journey-mapping skill writes the cycle state as it dispatches per-section subagents. Absence ⇒ no cycle ever ran." \
          "skills/journey-mapping/SKILL.md §\"Cycle protocol\""
      fi

      # Cycle 1 + Cycle 2 are non-negotiable per the iterative-discovery
      # protocol (≥1 discovery cycle + exactly 1 edge-probe cycle).
      HAS_CYCLE_1=$("$JQ" -r '.cycles["1"] != null' "$CYCLE_STATE_PATH" 2>/dev/null || echo "false")
      HAS_CYCLE_2=$("$JQ" -r '.cycles["2"] != null' "$CYCLE_STATE_PATH" 2>/dev/null || echo "false")
      if [ "$HAS_CYCLE_1" != "true" ] || [ "$HAS_CYCLE_2" != "true" ]; then
        pipeline_emit_phase_deny "4" \
          ".phase4-cycle-state.json is missing cycle-1 and/or cycle-2 records (has-cycle-1=${HAS_CYCLE_1}, has-cycle-2=${HAS_CYCLE_2}). Both are non-negotiable: ≥1 discovery cycle + exactly 1 edge-probe cycle." \
          "complete the cycle protocol — dispatch cycle-1 section agents (strict per-section parallel), then the cycle-2 edge-probe — before closing Phase 4." \
          "skills/journey-mapping/SKILL.md §\"Iterative discovery cycles\""
      fi

      # Cycle-roster completeness: for EVERY cycle recorded, the section
      # subagents must have all returned. dispatched-sections == returned-
      # sections (set equality, not just length). Catches the "dispatched
      # 7, only 5 came back, marked the cycle done anyway" failure mode.
      for cycle_id in 1 2; do
        DISPATCHED=$("$JQ" -c ".cycles[\"${cycle_id}\"][\"dispatched-sections\"] // [] | sort" "$CYCLE_STATE_PATH" 2>/dev/null || echo "[]")
        RETURNED=$("$JQ" -c ".cycles[\"${cycle_id}\"][\"returned-sections\"] // [] | sort" "$CYCLE_STATE_PATH" 2>/dev/null || echo "[]")
        if [ "$DISPATCHED" != "$RETURNED" ]; then
          DISPATCHED_COUNT=$(echo "$DISPATCHED" | "$JQ" 'length')
          RETURNED_COUNT=$(echo "$RETURNED" | "$JQ" 'length')
          pipeline_emit_phase_deny "4" \
            "Cycle ${cycle_id} dispatched-sections (${DISPATCHED_COUNT}) != returned-sections (${RETURNED_COUNT}). Some section agents did not return; the cycle is incomplete." \
            "wait for every dispatched section to return before authoring the journey map. Re-dispatch any stalled sections. The author step consumes the union of all section returns — partial returns mean partial coverage." \
            "skills/journey-mapping/SKILL.md §\"Cycle protocol\""
        fi
      done
      ;;
    5)
      # Phase 5 — coverage-expansion-state.json with at least pass-1 record.
      COV_STATE_PATH="$PROJECT_ROOT/tests/e2e/docs/coverage-expansion-state.json"
      if [ ! -f "$COV_STATE_PATH" ]; then
        pipeline_emit_phase_deny "5" \
          "tests/e2e/docs/coverage-expansion-state.json does not exist." \
          "invoke the \`coverage-expansion\` skill via the Skill tool. It writes the state file as it runs the per-pass pipeline." \
          "skills/onboarding/SKILL.md §\"Phase 5 — Coverage expansion\" + skills/coverage-expansion/SKILL.md"
      fi
      HAS_PASS_1=$("$JQ" -r '.passes["1"] != null' "$COV_STATE_PATH" 2>/dev/null || echo "false")
      if [ "$HAS_PASS_1" != "true" ]; then
        pipeline_emit_phase_deny "5" \
          "coverage-expansion-state.json reports no pass-1 record. Pass 1 (strict per-journey, compositional) is the foundation of every coverage-expansion mode." \
          "run at least Pass 1 of coverage-expansion before closing Phase 5." \
          "skills/coverage-expansion/SKILL.md §\"Non-negotiables\""
      fi

      # Phase-5 ordering (cross-cutting §12): a standard/depth run only
      # completes when ALL FIVE passes plus the cleanup/dedup step are
      # recorded in coverage-expansion-state.json. The cleanup commit
      # RECORDS passes 1-5 + cleanup and does NOT delete the state file;
      # the orchestrator deletes it only AFTER reviewer approval, as the
      # final post-approval act, then writes the Phase-5 ledger completion.
      # So at the moment this completion write lands, the state file must
      # still exist and carry the full record. (A breadth-mode run is the
      # documented single-pass exception — it records cleanup with a
      # `mode: breadth` marker and is exempt from the 5-pass requirement.)
      RUN_MODE_COV=$("$JQ" -r '.runMode // .mode // "standard"' "$COV_STATE_PATH" 2>/dev/null || echo "standard")
      if [ "$RUN_MODE_COV" != "breadth" ]; then
        MISSING_PASSES=""
        for pnum in 1 2 3 4 5; do
          HAS_P=$("$JQ" -r --arg p "$pnum" '.passes[$p] != null' "$COV_STATE_PATH" 2>/dev/null || echo "false")
          [ "$HAS_P" = "true" ] || MISSING_PASSES="${MISSING_PASSES} ${pnum}"
        done
        CLEANUP_RECORDED=$("$JQ" -r '
          (.cleanup != null) or (.cleanupRecorded == true) or (.passes["cleanup"] != null)
        ' "$COV_STATE_PATH" 2>/dev/null || echo "false")
        if [ -n "$MISSING_PASSES" ] || [ "$CLEANUP_RECORDED" != "true" ]; then
          pipeline_emit_phase_deny "5" \
            "coverage-expansion-state.json does not record the full five-pass run + cleanup. Missing pass record(s):${MISSING_PASSES:- none}; cleanup recorded: ${CLEANUP_RECORDED}. A standard/depth Phase 5 completes only after passes 1-5 AND the cleanup/dedup step are recorded." \
            "complete all five passes (compositional 1-3 + adversarial 4-5) and the cleanup/dedup step. The ordering is: RECORD passes 1-5 + cleanup in coverage-expansion-state.json → workflow-reviewer-phase5 approval → the orchestrator DELETES the state file as the final post-approval act → write this Phase-5 ledger completion. The state file must still be present and complete at this write (deletion happens post-approval, not before)." \
            "skills/coverage-expansion/SKILL.md §\"Five passes\" + cross-cutting §12 (phase-5 state-file ordering)"
        fi
      fi

      # Coverage-completeness check: Pass 1's dispatched-journeys + any
      # deferredJourneys[] entries must together cover the journey map's
      # full roster. Catches the "dispatched 8 of 41 journeys, called
      # exit-#2, marked Phase 5 complete" failure mode. The roster is
      # derived from the journey-map.md (one entry per `^#### j-` block).
      MAP_PATH="$PROJECT_ROOT/tests/e2e/docs/journey-map.md"
      if [ -f "$MAP_PATH" ]; then
        # Roster headings are canonical `### j-<slug>: <name>`; the prior
        # `^#### j-` pattern (4 hashes) never matched the real map and left
        # the coverage-completeness check dead. Accept `### j-` or `#### j-`.
        ROSTER_COUNT=$(grep -cE '^###[#]? j-' "$MAP_PATH" 2>/dev/null; true)
        ROSTER_COUNT=${ROSTER_COUNT:-0}
        DISPATCHED_COUNT=$("$JQ" -r '.passes["1"]["dispatched-journeys"] // [] | length' "$COV_STATE_PATH" 2>/dev/null || echo "0")
        DEFERRED_COUNT=$("$JQ" -r '.passes["1"]["deferredJourneys"] // [] | length' "$COV_STATE_PATH" 2>/dev/null || echo "0")
        DISPATCHED_COUNT=${DISPATCHED_COUNT:-0}
        DEFERRED_COUNT=${DEFERRED_COUNT:-0}
        TOTAL_ACCOUNTED=$((DISPATCHED_COUNT + DEFERRED_COUNT))

        if [ "$ROSTER_COUNT" -gt 0 ] && [ "$TOTAL_ACCOUNTED" -lt "$ROSTER_COUNT" ]; then
          UNCOVERED=$((ROSTER_COUNT - TOTAL_ACCOUNTED))
          pipeline_emit_phase_deny "5" \
            "Pass 1 coverage incomplete: journey-map.md lists ${ROSTER_COUNT} journeys; coverage-expansion-state.json records ${DISPATCHED_COUNT} dispatched + ${DEFERRED_COUNT} deferred = ${TOTAL_ACCOUNTED} accounted. ${UNCOVERED} journey(s) are silently missing. This is the silent-scope-compression failure mode." \
            "either (a) dispatch the remaining ${UNCOVERED} journey(s) through coverage-expansion Pass 1, OR (b) add a deferredJourneys[] entry for each missing journey with a reason (structural prefix OR an \"authorizer\" field carrying a verbatim user quote). Pre-emptive scope reduction without authorisation is denied." \
            "skills/coverage-expansion/SKILL.md §\"Two valid exits\" + §\"Deferral authorisation\""
        fi

        # Deferral authorisation: each deferredJourneys[] entry must have
        # a structural reason prefix OR an explicit authorizer quote.
        # Self-imposed reasons (budget-cap, session-length, auto-mode-stop)
        # without an authorizer field are silent scope narrowing.
        if [ "$DEFERRED_COUNT" -gt 0 ]; then
          BAD_DEFERRAL=$(
            "$JQ" -r '
              .passes["1"]["deferredJourneys"] // [] | .[] |
              select(
                ((.reason // "") | test("^(blocked-on-app-bug:|test-data-prerequisite:|user-authorised:)")) | not
              ) |
              select(((.authorizer // "") | length) == 0) |
              .journey // "<unknown>"
            ' "$COV_STATE_PATH" 2>/dev/null | head -1 || true
          )
          if [ -n "$BAD_DEFERRAL" ]; then
            pipeline_emit_phase_deny "5" \
              "deferredJourneys[] entry for \"${BAD_DEFERRAL}\" carries neither a structural reason prefix (\`blocked-on-app-bug:\`, \`test-data-prerequisite:\`, \`user-authorised:\`) nor an \`authorizer\` field with a verbatim user quote. Self-imposed deferrals (budget-cap, session-length, auto-mode-stop) without authorisation are silent scope narrowing." \
              "either dispatch this journey through Pass 1, or add a reason matching one of the allowed structural prefixes, or capture the user's verbatim authorisation in an \`authorizer\` field." \
              "skills/coverage-expansion/SKILL.md §\"Deferral authorisation\""
          fi
        fi
      fi

      ;;
    6)
      # Phase 6 — adversarial-findings ledger exists AND has substance.
      ADV_PATH="$PROJECT_ROOT/tests/e2e/docs/adversarial-findings.md"
      if [ ! -f "$ADV_PATH" ]; then
        pipeline_emit_phase_deny "6" \
          "tests/e2e/docs/adversarial-findings.md does not exist." \
          "invoke the \`bug-discovery\` skill (or the adversarial passes of coverage-expansion). They write the findings ledger as probes return." \
          "skills/onboarding/SKILL.md §\"Phase 6 — Bug discovery\" + skills/bug-discovery/SKILL.md"
      fi

      # Content check: the ledger must contain at least one per-journey
      # section block. The canonical schema (per
      # references/subagent-return-schema.md §3) uses `### j-<slug>` as
      # the per-journey section header. An empty ledger (just the
      # title) means no probe ever ran — the file exists but the
      # methodology was bypassed. grep -c always prints a count (even
      # 0) and exits 1 on no-match — capture stdout, ignore exit code.
      JOURNEY_BLOCKS=$(grep -c '^### j-' "$ADV_PATH" 2>/dev/null; true)
      JOURNEY_BLOCKS=${JOURNEY_BLOCKS:-0}
      if [ "$JOURNEY_BLOCKS" -lt 1 ]; then
        pipeline_emit_phase_deny "6" \
          "tests/e2e/docs/adversarial-findings.md exists but contains 0 per-journey section blocks (\`### j-<slug>\`). File existence alone is not bug-discovery; the ledger must record at least one probe." \
          "dispatch the bug-discovery probe subagents per journey (or the adversarial passes of coverage-expansion). Each probe appends a \`### j-<slug>\` section to the ledger as it returns." \
          "skills/bug-discovery/SKILL.md + achilles-protocol/references/subagent-return-schema.md §3"
      fi
      ;;
    7)
      # Phase 7 — .env.example exists at project root.
      ENV_EXAMPLE_PATH="$PROJECT_ROOT/.env.example"
      if [ ! -f "$ENV_EXAMPLE_PATH" ]; then
        pipeline_emit_phase_deny "7" \
          ".env.example does not exist at the project root." \
          "invoke the \`secrets-sweep\` skill. It writes .env.example as it extracts literals from the test suite." \
          "skills/onboarding/SKILL.md §\"Phase 7 — Secrets sweep\" + skills/secrets-sweep/SKILL.md"
      fi
      ;;
    8)
      # Phase 8 — qa-summary-deck.{html,pdf} exist at project root.
      DECK_HTML="$PROJECT_ROOT/qa-summary-deck.html"
      DECK_PDF="$PROJECT_ROOT/qa-summary-deck.pdf"
      MISSING_DECK=""
      [ -f "$DECK_HTML" ] || MISSING_DECK="qa-summary-deck.html"
      [ -f "$DECK_PDF" ]  || MISSING_DECK="${MISSING_DECK:+$MISSING_DECK + }qa-summary-deck.pdf"
      if [ -n "$MISSING_DECK" ]; then
        pipeline_emit_phase_deny "8" \
          "$MISSING_DECK missing from project root." \
          "invoke the \`work-summary-deck\` skill. It writes the HTML deck and renders the PDF." \
          "skills/onboarding/SKILL.md §\"Phase 8 — Report\" + skills/work-summary-deck/SKILL.md"
      fi
      ;;
  esac
}

pipeline_ledger_write_main onboarding_check_deliverables
