#!/bin/bash
# perf-onboarding-ledger-write-gate.sh — schema + state-machine integrity
#                                        gate for writes to the perf
#                                        onboarding status ledger.
#
# Hook    : PreToolUse:Write|Edit
# Mode    : DENY (blocks the write before it lands on disk)
# State   : validates shape via hooks/lib/validator.bundle.mjs (the
#           perf-onboarding-status schema is inlined in the bundle at build
#           time; source schemas/perf-onboarding-status.schema.json), plus
#           the pre-existing tests/perf/docs/perf-onboarding-status.json
#           (when present) to validate the state-machine transition.
# Env     : none
#
# Why
# ---
# The ledger is the single source of truth for the perf pipeline state. A
# corrupted ledger silently degrades every downstream gate. This hook is
# the guard at the only mutation point.
#
# What it gates
# -------------
# 1. **Shape validation.** Proposed contents must validate against the
#    perf-onboarding-status schema inlined in hooks/lib/validator.bundle.mjs.
# 2. **No phase-skip transitions.**
# 3. **No reviewerVerdict: approved without a handoverEnvelope.**
# 4. **Actor-identity on approval transitions** (separation of duties) —
#    also required for a top-level `.status` → `complete` | `aborted`
#    transition, the write that retires the session's governance.
# 5. **Mode authorisation** (runMode/modeAuthorizer co-location).
# 6. **Silent-allow for non-ledger writes** (only acts on perf ledger path).
# 7. **Per-phase positive-deliverable checks** at phase → completed transitions.
#
# Canonical reference
# -------------------
# schemas/perf-onboarding-status.schema.json
# skills/perf-onboarding/SKILL.md §"Status ledger + workflow reviewer"
# hooks/lib/validator.bundle.mjs (generated by `npm run build:validator`)
#
# Failure → action
# ----------------
# Shape invalid                      → DENY with schema-path + bad field
# Phase-skip without approval        → DENY naming the missing in-between phase
# reviewerVerdict approved w/o handover → DENY naming the empty field

set -uo pipefail

. "$(dirname "${BASH_SOURCE[0]}")/lib/hook-io.sh"
hook_lib pipeline-ledger-write.sh
hook_jq_init fatal

pipeline_config perf
PIPELINE_SCHEMA_NAME="perf-onboarding-status"
PIPELINE_APPROVER_TYPES="perf-reviewer"
PIPELINE_PHASE_COUNT=7
PIPELINE_MSG_PHASE_LABEL='Perf Phase'
PIPELINE_MSG_DELIVERABLE_LEDGER='perf ledger'
PIPELINE_MSG_DELIVERABLE_WHY=''

# ---------------------------------------------------------------------------
# Per-phase positive-deliverable checks for the perf pipeline.
# When a phase's status flips to "completed" in the proposed write, the
# canonical deliverables for that phase must already exist on disk.
#
# Per-phase manifests:
#   Phase 1 (Scaffold)       — tests/perf/perf-onboarding.config.json +
#                              tests/perf/lib/ is non-empty
#   Phase 2 (Readiness)      — tests/perf/docs/readiness.md
#   Phase 3 (Scenario-model) — tests/perf/docs/scenario-model.md + sentinel
#                              `<!-- perf-onboarding:scenario-model -->` on
#                              line 1 + ≥1 file under tests/perf/scenarios/*.js
#   Phase 4 (Baseline)       — ≥1 file under tests/perf/baselines/*.json
#   Phase 5 (Load-run)       — ≥1 file under tests/perf/results/*.json
#   Phase 6 (Threshold-gate) — tests/perf/docs/threshold-verdict.json +
#                              jq -e '.deliberateBreach | length > 0' passes
#   Phase 7 (Report)         — tests/perf/docs/perf-report.md + line 1 is
#                              `<!-- perf-onboarding:report -->`
# ---------------------------------------------------------------------------
perf_check_deliverables() {
  case "$1" in
    1)
      # Phase 1 (Scaffold): config file + non-empty lib/ directory.
      CONFIG_PATH="$PROJECT_ROOT/tests/perf/perf-onboarding.config.json"
      LIB_DIR="$PROJECT_ROOT/tests/perf/lib"
      if [ ! -f "$CONFIG_PATH" ]; then
        pipeline_emit_phase_deny "1 (Scaffold)" \
          "tests/perf/perf-onboarding.config.json does not exist." \
          "complete the scaffold phase: create perf-onboarding.config.json with baseline targets, VU limits, and threshold definitions." \
          "skills/perf-onboarding/SKILL.md §\"Phase 1 — Scaffold\""
      fi
      # lib/ must be a non-empty directory.
      LIB_HAS_FILES="false"
      if [ -d "$LIB_DIR" ]; then
        LIB_FILE_COUNT=$(find "$LIB_DIR" -maxdepth 2 -type f 2>/dev/null | wc -l | tr -d ' ')
        [ "${LIB_FILE_COUNT:-0}" -gt 0 ] && LIB_HAS_FILES="true"
      fi
      if [ "$LIB_HAS_FILES" != "true" ]; then
        pipeline_emit_phase_deny "1 (Scaffold)" \
          "tests/perf/lib/ does not exist or is empty." \
          "populate tests/perf/lib/ with shared k6 helper modules (e.g. auth.js, thresholds.js) before closing Phase 1." \
          "skills/perf-onboarding/SKILL.md §\"Phase 1 — Scaffold\""
      fi
      ;;
    2)
      # Phase 2 (Readiness): readiness.md.
      READINESS_PATH="$PROJECT_ROOT/tests/perf/docs/readiness.md"
      if [ ! -f "$READINESS_PATH" ]; then
        pipeline_emit_phase_deny "2 (Readiness)" \
          "tests/perf/docs/readiness.md does not exist." \
          "complete the readiness assessment and write the readiness document before closing Phase 2." \
          "skills/perf-onboarding/SKILL.md §\"Phase 2 — Readiness\""
      fi
      ;;
    3)
      # Phase 3 (Scenario-model): scenario-model.md + sentinel + ≥1 scenario file.
      SCENARIO_MODEL_PATH="$PROJECT_ROOT/tests/perf/docs/scenario-model.md"
      if [ ! -f "$SCENARIO_MODEL_PATH" ]; then
        pipeline_emit_phase_deny "3 (Scenario-model)" \
          "tests/perf/docs/scenario-model.md does not exist." \
          "author the scenario model document before closing Phase 3." \
          "skills/perf-onboarding/SKILL.md §\"Phase 3 — Scenario-model\""
      fi
      SCENARIO_FIRST_LINE=$(head -n 1 "$SCENARIO_MODEL_PATH" 2>/dev/null || echo "")
      if [ "$SCENARIO_FIRST_LINE" != "<!-- perf-onboarding:scenario-model -->" ]; then
        pipeline_emit_phase_deny "3 (Scenario-model)" \
          "tests/perf/docs/scenario-model.md is missing the line-1 sentinel \`<!-- perf-onboarding:scenario-model -->\`. Got: \"${SCENARIO_FIRST_LINE:0:80}\"" \
          "regenerate scenario-model.md via the perf-onboarding skill. The sentinel is its authorship marker." \
          "skills/perf-onboarding/SKILL.md §\"Phase 3 — Scenario-model\""
      fi
      SCENARIOS_DIR="$PROJECT_ROOT/tests/perf/scenarios"
      SCENARIO_FILE_COUNT=$(find "$SCENARIOS_DIR" -maxdepth 1 -name "*.js" -type f 2>/dev/null | wc -l | tr -d ' ')
      if [ "${SCENARIO_FILE_COUNT:-0}" -lt 1 ]; then
        pipeline_emit_phase_deny "3 (Scenario-model)" \
          "no *.js scenario files found under tests/perf/scenarios/." \
          "create at least one k6 scenario script in tests/perf/scenarios/ before closing Phase 3." \
          "skills/perf-onboarding/SKILL.md §\"Phase 3 — Scenario-model\""
      fi
      ;;
    4)
      # Phase 4 (Baseline): ≥1 baseline JSON file.
      BASELINES_DIR="$PROJECT_ROOT/tests/perf/baselines"
      BASELINE_FILE_COUNT=$(find "$BASELINES_DIR" -maxdepth 1 -name "*.json" -type f 2>/dev/null | wc -l | tr -d ' ')
      if [ "${BASELINE_FILE_COUNT:-0}" -lt 1 ]; then
        pipeline_emit_phase_deny "4 (Baseline)" \
          "no *.json baseline files found under tests/perf/baselines/." \
          "run the baseline measurement and write at least one baseline JSON file before closing Phase 4." \
          "skills/perf-onboarding/SKILL.md §\"Phase 4 — Baseline\""
      fi
      ;;
    5)
      # Phase 5 (Load-run): ≥1 results JSON file.
      RESULTS_DIR="$PROJECT_ROOT/tests/perf/results"
      RESULTS_FILE_COUNT=$(find "$RESULTS_DIR" -maxdepth 1 -name "*.json" -type f 2>/dev/null | wc -l | tr -d ' ')
      if [ "${RESULTS_FILE_COUNT:-0}" -lt 1 ]; then
        pipeline_emit_phase_deny "5 (Load-run)" \
          "no *.json result files found under tests/perf/results/." \
          "complete at least one load-run pass and write its results JSON before closing Phase 5." \
          "skills/perf-onboarding/SKILL.md §\"Phase 5 — Load-run\""
      fi
      ;;
    6)
      # Phase 6 (Threshold-gate): threshold-verdict.json + deliberateBreach non-empty.
      VERDICT_PATH="$PROJECT_ROOT/tests/perf/docs/threshold-verdict.json"
      if [ ! -f "$VERDICT_PATH" ]; then
        pipeline_emit_phase_deny "6 (Threshold-gate)" \
          "tests/perf/docs/threshold-verdict.json does not exist." \
          "run the threshold evaluation and write threshold-verdict.json before closing Phase 6." \
          "skills/perf-onboarding/SKILL.md §\"Phase 6 — Threshold-gate\""
      fi
      DELIBERATE_LEN=$("$JQ" -r 'if (.deliberateBreach | type) == "array" then (.deliberateBreach | length) else -1 end' "$VERDICT_PATH" 2>/dev/null || echo "-1")
      case "$DELIBERATE_LEN" in ''|*[!0-9-]*) DELIBERATE_LEN=-1 ;; esac
      if [ "$DELIBERATE_LEN" -lt 1 ]; then
        pipeline_emit_phase_deny "6 (Threshold-gate)" \
          "tests/perf/docs/threshold-verdict.json exists but .deliberateBreach is empty or missing. The threshold gate requires explicit deliberate-breach analysis with ≥1 entry." \
          "populate the deliberateBreach field in threshold-verdict.json with at least one threshold deliberation record." \
          "skills/perf-onboarding/SKILL.md §\"Phase 6 — Threshold-gate\""
      fi
      ;;
    7)
      # Phase 7 (Report): perf-report.md + sentinel on line 1.
      REPORT_PATH="$PROJECT_ROOT/tests/perf/docs/perf-report.md"
      if [ ! -f "$REPORT_PATH" ]; then
        pipeline_emit_phase_deny "7 (Report)" \
          "tests/perf/docs/perf-report.md does not exist." \
          "author the performance report before closing Phase 7." \
          "skills/perf-onboarding/SKILL.md §\"Phase 7 — Report\""
      fi
      REPORT_FIRST_LINE=$(head -n 1 "$REPORT_PATH" 2>/dev/null || echo "")
      if [ "$REPORT_FIRST_LINE" != "<!-- perf-onboarding:report -->" ]; then
        pipeline_emit_phase_deny "7 (Report)" \
          "tests/perf/docs/perf-report.md is missing the line-1 sentinel \`<!-- perf-onboarding:report -->\`. Got: \"${REPORT_FIRST_LINE:0:80}\"" \
          "regenerate perf-report.md via the perf-onboarding skill. The sentinel is its authorship marker." \
          "skills/perf-onboarding/SKILL.md §\"Phase 7 — Report\""
      fi
      ;;
  esac
}

pipeline_ledger_write_main perf_check_deliverables
