#!/bin/bash
# subagent-return-schema-guard.sh — JSON-Schema validator for subagent returns
#
# Hook    : PostToolUse:Agent
# Mode    : WARN (initial release; will flip to DENY in a follow-up after
#           false-positive rate is calibrated on a representative run)
# State   : none
# Env     : none
#
# Rule
# ----
# Validates subagent returns against JSON-Schema definitions in
# schemas/subagent-returns/<role>.schema.json. Validation runs through
# hooks/lib/validator.bundle.mjs — a self-contained bundle (Ajv 8,
# draft 2020-12, all schemas inlined) generated by `npm run build:validator`.
# No node_modules or repo-root resolution required at hook runtime.
#
# Schema coverage:
#   composer-<slug>            → schemas/subagent-returns/composer.schema.json
#   reviewer-<slug>            → schemas/subagent-returns/reviewer-inloop.schema.json
#   probe-<slug>               → schemas/subagent-returns/probe.schema.json
#   phase-validator-<N>        → schemas/subagent-returns/phase-validator.schema.json
#   workflow-reviewer-<unit>   → schemas/subagent-returns/workflow-reviewer.schema.json
#                                (post-only mapping — see lib/schema-role-map.sh)
#
# No-schema roles (silent allow on schema step):
#   process-validator-*, phase1-*, stage2-*, cleanup-*, bare j-/sj-
#
# The handover envelope is validated as part of the schema (handover is a
# required nested key in every role schema).
#
# Canonical reference
# -------------------
# schemas/subagent-returns/*.schema.json  — single source of truth
# skills/element-interactions/references/subagent-return-schema.md §4.2
#
# Failure → action
# ----------------
# Schema validation failure → WARN (systemMessage with validator error details)
# Handover envelope issues  → WARN (same channel)

set -euo pipefail

# Resolve jq.
JQ="$(dirname "${BASH_SOURCE[0]}")/bin/jq"
[ -x "$JQ" ] || JQ="$(command -v jq || true)"
if [ -z "$JQ" ]; then
  echo "[$(basename "${BASH_SOURCE[0]}")] FATAL: jq not found at \$HOOK_DIR/bin/jq nor on PATH." >&2
  exit 1
fi

# Resolve node (must be on PATH for the validator bundle).
NODE="$(command -v node || true)"
if [ -z "$NODE" ]; then
  echo "[$(basename "${BASH_SOURCE[0]}")] FATAL: node not found on PATH. Install Node.js." >&2
  exit 1
fi

# Shared no-skip messaging library.
# shellcheck source=lib/no-skip-messaging.sh
HOOK_LIB_DIR="$(dirname "${BASH_SOURCE[0]}")/lib"
if [ -f "$HOOK_LIB_DIR/no-skip-messaging.sh" ]; then
  source "$HOOK_LIB_DIR/no-skip-messaging.sh"
else
  no_skip_messaging_block() { echo ""; }
fi

# Path to the self-contained validator bundle (co-located in lib/;
# generated by `npm run build:validator`, shipped in the package tarball).
VALIDATOR="$HOOK_LIB_DIR/validator.bundle.mjs"

emit_warn() {
  local msg="$1
$(no_skip_messaging_block)"
  "$JQ" -n --arg m "$msg" '{
    "systemMessage": $m,
    "suppressOutput": false
  }'
}

# --- input ---
INPUT=$(cat)
TOOL_NAME=$(echo "$INPUT" | "$JQ" -r '.tool_name // empty')
[ "$TOOL_NAME" != "Agent" ] && exit 0

DESCRIPTION=$(echo "$INPUT" | "$JQ" -r '.tool_input.description // ""')

# Shared role-mapping. Single source of truth — same file is sourced by
# the PreToolUse half of the contract (subagent-schema-preread-gate.sh).
# This guard uses the post-only superset resolve_schema_role_post(),
# which additionally maps workflow-reviewer-* (the preread gate must
# not enforce that role — rationale in lib/schema-role-map.sh).
# Unknown prefix → silent allow (out of scope). Known prefix with no
# schema (process-validator-*) → empty SCHEMA_ROLE, continues to the
# handover-envelope warn path below; the schema step is skipped via
# the `if [ -n "$SCHEMA_ROLE" ]` guard.
# shellcheck source=lib/schema-role-map.sh
# shellcheck disable=SC1091
. "$HOOK_LIB_DIR/schema-role-map.sh"
if ! SCHEMA_ROLE=$(resolve_schema_role_post "$DESCRIPTION"); then
  exit 0
fi

# Extract the subagent's textual return.
# PostToolUse:Agent payloads carry the return in a few shapes.
RESPONSE=$(
  echo "$INPUT" | "$JQ" -r '
    [
      (.tool_response.output? | if type == "array" then map(.text? // (. | tostring)) | join("\n") elif type == "string" then . else (. | tostring) end),
      (.tool_response.result? // empty | tostring),
      (if (.tool_response | type) == "string" then .tool_response else empty end)
    ] | map(select(. != null and . != "")) | unique | join("\n")
  ' 2>/dev/null || echo ""
)

if [ -z "$RESPONSE" ]; then
  RESPONSE=$(echo "$INPUT" | "$JQ" -r '
    if (.tool_response // null) == null then ""
    elif (.tool_response | type) == "string" then .tool_response
    else (.tool_response | tostring)
    end
  ' 2>/dev/null || echo "")
fi

case "$RESPONSE" in
  ""|"null"|"{}"|"[]") exit 0 ;;
esac

# === Handover envelope parse ===============================================
# Extract the envelope's cycle field for the numeric sanity check below.
# Deeper envelope structure is validated by the JSON-Schema step.
# The handover block is YAML-indented under a top-level `handover:` line.
HANDOVER_CYCLE=""
HANDOVER_WARNS=()

if echo "$RESPONSE" | grep -qE '(^|\n)handover:[[:space:]]*$'; then
  HANDOVER_BLOCK=$(echo "$RESPONSE" | awk '
    /^handover:[[:space:]]*$/ { in_block = 1; next }
    in_block {
      if (/^[[:space:]]+/ || /^$/) { print; next }
      exit
    }
  ' || true)
  HANDOVER_CYCLE=$(echo "$HANDOVER_BLOCK" | grep -E '^[[:space:]]+cycle:' | head -1 | sed -E 's/^[[:space:]]+cycle:[[:space:]]*//' | tr -d '[:space:]' || true)
fi

# Numeric cycle sanity.
if [ -n "$HANDOVER_CYCLE" ] && ! echo "$HANDOVER_CYCLE" | grep -qE '^[0-9]+$'; then
  HANDOVER_WARNS+=("handover: cycle: '${HANDOVER_CYCLE}' is not a non-negative integer (§2.0)")
fi

# === JSON-Schema validation via the bundled validator ======================
# Only run for roles that have a schema. process-validator has no schema
# at this version — it falls through to the handover-only warn path below.
SCHEMA_ERRORS=""
if [ -n "$SCHEMA_ROLE" ]; then
  # Write RESPONSE to a temp file for the validator bundle.
  TMPFILE=$(mktemp /tmp/subagent-schema-guard-XXXXXX.yaml)
  trap 'rm -f "$TMPFILE"' EXIT
  printf '%s' "$RESPONSE" > "$TMPFILE"

  # Invoke the self-contained validator bundle (all schemas inlined — no
  # repo-root cwd or node_modules needed). Success prints nothing, so
  # SCHEMA_ERRORS stays empty on valid returns.
  if [ -f "$VALIDATOR" ]; then
    SCHEMA_ERRORS=$("$NODE" "$VALIDATOR" validate "$SCHEMA_ROLE" "$TMPFILE" 2>&1) || true
  else
    SCHEMA_ERRORS="validator bundle missing at ${VALIDATOR} — run npm run build:validator (in-repo) or reinstall @civitas-cerebrum/achilles"
  fi
fi

# === Emit warning if any issues found =====================================
if [ ${#HANDOVER_WARNS[@]} -eq 0 ] && [ -z "$SCHEMA_ERRORS" ]; then
  exit 0
fi

WARNING="[WARN] Subagent return validation surfaced issues.

Description: \"${DESCRIPTION}\"
Role:        ${SCHEMA_ROLE:-${DESCRIPTION%%[-:]*}}"

if [ -n "$SCHEMA_ERRORS" ]; then
  WARNING="${WARNING}

Schema validation errors (schemas/subagent-returns/${SCHEMA_ROLE}.schema.json):
${SCHEMA_ERRORS}"
fi

if [ ${#HANDOVER_WARNS[@]} -gt 0 ]; then
  WARNING="${WARNING}

Handover envelope (§2.0):"
  for item in "${HANDOVER_WARNS[@]}"; do
    WARNING="${WARNING}
  - ${item}"
  done
fi

WARNING="${WARNING}

The canonical return schemas are at:
  schemas/subagent-returns/<role>.schema.json

Re-dispatch the subagent with a brief that quotes the schema constraints
verbatim. This warning is non-blocking; a follow-up release will promote
it to BLOCK once the false-positive rate is calibrated."

emit_warn "$WARNING"

exit 0
